-- Sonesta AWARDED the Executive Office AHU replacement — 2026-09-21.
-- Leroy Chisholm (LCHISHOLM@sonesta.com) emailed the Sonesta service agreement
-- to treycooper@candcontracting.com (Gmail msg 1a0c65385e5b887a): "Congratulations
-- on winning the service bid on the upcoming AC UNIT replacement."
--
-- CC-2026-AHU: submitted -> won. $27,900. First formal C&C service CONTRACT
-- (everything before this was proposal -> invoice). Invoice 1054 books the 50%
-- deposit but is NOT sent to the client yet — it is with Beverley and Donald for
-- internal review, so sent_at stays null until Leroy actually receives it.
--
-- Re-runnable: the update is idempotent, events and notes are `where not exists`
-- guarded, and the invoice insert is on-conflict-do-nothing.

update cc_leads
set stage       = 'won',
    next_action = 'BLOCKED on insurance. Do not send the signed contract or invoice 1054 to '
                  'Leroy until (a) Beverley and Donald approve and (b) the general liability '
                  'policy is reinstated and a COI can be issued naming Sonesta and the property '
                  'owner as additional insureds. Contract Sec.9(F) withholds ALL payment, the '
                  '$13,950 deposit included, until compliance is evidenced.',
    updated_at  = '2026-09-21T23:35:41Z'
where lead_ref = 'CC-2026-AHU';

-- The deposit invoice. Built 2026-09-21, verified, NOT yet sent to the client.
-- expected_at is left null on purpose: net-30 cannot start running from a date
-- the invoice has not been delivered on.
insert into cc_invoices
  (invoice_no, lead_id, description, amount, sent_at, expected_at, paid_at, method, notes)
select v.invoice_no, l.id, v.description, v.amount, v.sent_at::date,
       v.expected_at::date, v.paid_at::date, v.method, v.notes
from (values
  (1054, 'CC-2026-AHU',
   'Executive Office AC replacement — 50% deposit', 13950.00,
   null, null, null, null,
   'NOT SENT TO CLIENT YET. Built 2026-09-21 and sent to Beverley and Donald for review only. '
   '$27,900 job on 50/50 terms; balance of $13,950 due on completion. Generated by '
   '"C&C Contracting/Invoice Template/build_invoice_1054.py". Releasing this deposit is what '
   'starts the Trane order against a ~16-week lead time, so it gates the 10/19 start date.')
) as v(invoice_no, lead_ref, description, amount, sent_at, expected_at, paid_at, method, notes)
join cc_leads l on l.lead_ref = v.lead_ref
on conflict (invoice_no) do nothing;

insert into cc_events (lead_id, title, kind, starts_at, notes)
select l.id, v.title, v.kind, v.starts_at::timestamptz, v.notes
from (values
  ('CC-2026-AHU', 'WON — Sonesta awarded the AHU replacement', 'other', '2026-09-21T23:35:41Z',
   'Leroy emailed the Sonesta service agreement (Gmail msg 1a0c65385e5b887a) and asked for a '
   'signed copy plus COI, workers compensation and auto certificates. $27,900. Beat RCAC '
   'Mechanical''s $29,300 estimate by $1,400.'),
  ('CC-2026-AHU', 'Contract signed and redlined', 'other', '2026-09-21T23:58:00Z',
   'Signed by Charles Cooper III, President. Three corrections made to Sonesta''s form before '
   'signature, all disclosed to the client: entity name Inc. -> LLC, notice address corrected, '
   'and the 50/50 payment terms written into the Statement of Work. Files in '
   '"C&C Contracting/Contracts/" — AS-RECEIVED, REDLINED and SIGNED.'),
  ('CC-2026-AHU', 'Sent to Beverley and Donald for internal review', 'call', '2026-09-22T03:05:07Z',
   'Signed agreement + invoice 1054 emailed to bchisholm.bc@gmail.com and biggerdon.dc@gmail.com '
   '(Gmail thread 1a0c7130709197d7). Leroy deliberately NOT copied. Awaiting their approval and '
   'an answer on the general liability reinstatement.'),
  ('CC-2026-AHU', 'Contract commencement date', 'other', '2026-10-19T12:00:00Z',
   'Per Section 2(A) of the Sonesta service contract. Expiration 12/31/2026. Sonesta may '
   'terminate without cause on 30 days notice under Section 2(B), which is real exposure '
   'against the 16-week Trane lead time unless the deposit lands first.')
) as v(lead_ref, title, kind, starts_at, notes)
join cc_leads l on l.lead_ref = v.lead_ref
where not exists (
  select 1 from cc_events e where e.lead_id = l.id and e.title = v.title
);

insert into cc_notes (lead_id, body)
select l.id, v.body
from (values
  ('CC-2026-AHU',
   'AWARDED 2026-09-21. $27,900, term 10/19/2026 to 12/31/2026. C&C''s first formal service '
   'CONTRACT with Sonesta rather than a proposal-to-invoice job. Contract is Sonesta''s own form, '
   'version 2019.04.24, 13 pages.'),
  ('CC-2026-AHU',
   'REDLINE 1 — ENTITY. Sonesta''s form named the vendor "C&C Contracting Inc." in three places: '
   'the recitals, the Section 11 notice block and the signature block. The registered Florida '
   'entity is C&C Contracting LLC, SunBiz L25000304206. Florida rule: an L document number is an '
   'LLC, a profit corporation gets a P. There is no "Inc." — signing as a nonexistent entity '
   'risks piercing to Charles personally and lets Sonesta argue the contract never bound the '
   'company. Corrected in all three places and disclosed in the covering email.'),
  ('CC-2026-AHU',
   'REDLINE 2 — PAYMENT TERMS. The Statement of Work carried "Fees: $27,900.00" and nothing else. '
   'Section 3(B) otherwise defaults to MONTHLY invoicing paid NET 30 IN ARREARS, and Section 13 '
   'makes the Agreement control over the SOW wherever they conflict — so the 50/50 terms from the '
   'approved proposal had to be written INTO the SOW or they evaporated on signature. Added: 50% '
   'deposit $13,950 at signing, 50% balance $13,950 on completion. CHECK THIS ON EVERY SONESTA '
   'FORM JOB — the fan-coil contract will have the same hole.'),
  ('CC-2026-AHU',
   'REDLINE 3 — NOTICE ADDRESS. Section 11 listed only "Melbourne, Florida,32901". Corrected to '
   '1481 Mosswood Dr, Melbourne, FL 32935. The ZIP on their form was wrong, which matters because '
   'that is the address legal notices and termination letters go to.'),
  ('CC-2026-AHU',
   'BLOCKER — GENERAL LIABILITY IS CANCELLED. Section 9 requires $3,000,000 CGL, $2,000,000 '
   'professional liability, $1,000,000 auto and statutory workers comp with $1,000,000 employers '
   'liability, with Sonesta AND the property owner as additional insureds, carriers rated A-X. '
   'But per Soma Insurance 2026-08-16, C&C''s Evanston policy 3AB014502 was CANCELLED EFFECTIVE '
   '2026-08-01 for non-payment — Imperial PFS account WAS-602024, $1,002.82 past due to request '
   'reinstatement. No reinstatement confirmation exists in either the C&C or personal inbox as of '
   '2026-09-21. Section 9(F) relieves Sonesta of ANY duty to pay, deposit included, until '
   'compliance is evidenced. Even once reinstated, our stated $1M GL + $2M umbrella is short of '
   'Section 9, and professional liability does not appear to be carried at all. Raised with '
   'Beverley and Donald 2026-09-21.'),
  ('CC-2026-AHU',
   'OPEN — SUBCONTRACTOR CONSENT. Section 10 treats subcontracting as an assignment requiring '
   'Sonesta''s PRIOR WRITTEN consent; using a sub without it is cause for immediate termination. '
   'Trane factory technicians perform the controls work and unit startup per the scope, so get '
   'that consent in writing. Same unresolved contractor-of-record question as CC-2026-FANCOIL: '
   'the SOW represents that "C&C Contracting maintains all required state, county, and local '
   'licenses" while the CGC application has been on hold since 2026-07-14.'),
  ('CC-2026-AHU',
   'NOTE — DISPUTE FORUM. Section 17 sends any dispute to binding arbitration in Boston, '
   'Massachusetts under Massachusetts law with three arbitrators, each side paying its own costs. '
   'On a $27,900 job, arbitrating anything costs more than the contract is worth. Standard on '
   'Sonesta''s form, but it means the practical remedy here is the lien, not the contract.')
) as v(lead_ref, body)
join cc_leads l on l.lead_ref = v.lead_ref
where not exists (
  select 1 from cc_notes n where n.lead_id = l.id and n.body = v.body
);
